### ISSUE TITLE
ts: Module '"@solana-developers/helpers"' has no exported member 'createAccountsMintsAndTokenAccounts'

### ISSUE THREAD

**Issue by heyAyushh** [solana-developers/helpers#40] opened 2024-08-20 22:39 UTC
```import { createAccountsMintsAndTokenAccounts } from '@solana-developers/helpers';```
createAccountsMintsAndTokenAccounts is not found. 

```
  "dependencies": {
    "@solana-developers/helpers": "^2.3.0",
  },
```

**Comment by mikemaccana** [comment] 2024-08-23 14:00
Dupe of #42 (this is older but the other one has more comments).

**Closed by mikemaccana** 2024-08-23 14:00 UTC
